### ISSUE TITLE
[2.2.2] Meeting Minutes (Client Meeting)

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#13]
# Issue Details

## Description
Document the minutes from the client meeting. This will enable us to validate and analyze the main points to further clarify key issues in a follow-up email with our client. 

## Goals
Have a summary of key points taken from the client meeting.

## Success or Completion Criteria
A Meeting Minutes Document.

## Allocated Time
0.5 Day

**Start Date:** 07/09/23, 1100
**End Date:** 07/09/23, 1800

**Comment by git-clone-xen** [comment]
**Conclusions from insights provided by Client.**

Roles: Group all staff members into 1 role, then further split the roles into sub-roles within the system application. (1 actor to represent all staff roles in diagrams)

Maintenance: Considered. Maintenance terminals can exist between the routes from SG to KL, and vice versa.

Overload: Assist. conductor & cleaner may take on 3 carriages for a shift, and it would be classified as work overload. 

Overwork: 40hrs/week.

Train: No limitation on where to start/stop, could be SG/KL.

Shifts: 4 hours/shift.

Data history retained: 1 Year

User load: Not required, not a concern

Visualization: If staff worked too little = overstaffed, if staff overworked = hire more staff. 

Preference: No indication = Missed deadline submission = No preference. 

Train schedule: Up to us, reference from common train schedules. 

Scalability: Manager able to do more stuff, able to add more things

Main purpose: Interactive visualization tool

Questions:
Does the manager need to know if a train requires/currently going through maintenance?

**Comment by git-clone-xen** [comment]
# Issue Comments

## Description
Meeting minutes from the 15 minutes consultation session with the client. 
- Clarified most of the questions and concerns we had. 

## Changes to success or completion criteria? 
No changes, Criteria Completed.

Start Date: 07/09/23, 1100
End Date: 07/09/23, 1800
