### ISSUE TITLE
[6.1] Record Video (Client Meeting)

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#14]
Description: Take a video recording of the client meeting.

Goals: Have a video recording of the meeting to observe the client's behaviour (body language, tone etc.)

Success or Completion Criteria: Video of the meeting.

Allocated Time: 15mins.

Start Date: 07/09/23, 1100
End Date: 07/09/23, 1115

**Comment by alanwml** [comment]
## Issue Comments

### Description
Recorded a video of the Client meeting that we had on 07/09/2023, 1100 hours. I have also uploaded the video onto Youtube.
- [Video of Meeting with Client](https://youtu.be/YmCxSyWhj04)

### Changes to success or completion criteria? y/n (if y, describe)
No changes, Criteria Completed!

Start Date: 07/09/23, 1100
End Date: 07/09/23, 1800
