### ISSUE TITLE
[6.3] Interview the client (Client Meeting) [TBD]

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#16]
Description: Ask the client questions about the project during the client meeting.

Goals: Obtain information from the client efficiently to clarify requirements for the project.

Success or Completion Criteria: Finish asking high priority questions.

Allocated Time: 15mins

Start Date: 07/09/23, 1100
End Date: 07/09/23, 1115

**Comment by motorfireman** [comment]
### **Description:** 
Client wants the focus to be the software to be an interactive tool that adds in manual process of allocating tasks. Should not be an automated software system that do the task assignment on its own. Manager should be able to drag and drop the employees to the respective shift. 

### **Changes to success or completion criteria? Y/N (if yes, describe):** 
No

Start Date: 07/09/23, 1100
End Date: 07/09/23, 1115
