### ISSUE TITLE
Initial Requirement 4 Lofi-Prototyping

### ISSUE THREAD

**Issue by Alan2201038** [Alan2201038/INF2001-P5-7#19]
Description: Prototyping based on Initial Requirement 4.

Goals: Create a Prototype based on the Requirement.

Success or Completion Criteria: Prototype Figma.

Allocated Time: 2 days

Start Date: 31/08/23
End Date: 01/09/23

Main Task :  [Create lo-fi prototypes/wireframes based for the initial requirements](https://github.com/users/Alan2201038/projects/1/views/1?pane=issue&itemId=37133700)

**Comment by git-clone-xen** [comment]
# Issue Comments

## Description
Update the manager assign function. It should first be sorted by SG/KL > Month > Day > Shifts > Job Roles. display the 3 employees based on preference and lowest hours.

## Changes to success or completion criteria? 
No changes, Criteria Completed.

Start Date: 07/09/23
End Date: 09/09/23, 2359
