### ISSUE TITLE
[1.3.2.1] Creating Functional Requirements

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#26]
# Issue Details

## Description
Look at the gathered requirements and finalize them into a set of functional requirements. Remove UI requirements, split requirements up, edit requirements to ensure that they are concise (eg. immediately = 3s?). 

## Goals
To have a list of Functional Requirements first before validating and making any changes we deem is important.

## Success or Completion Criteria
Created a list of Functional Requirements for further validation.

## Allocated Time
4 days

**Start Date:** 08/09/23, 0900
**End Date:** 13/09/23, 2359

**Comment by Alan2201038** [comment]
No

**Comment by git-clone-xen** [comment]
Created some starting FRs on 11/09/23 :  

FR1: The system shall provide a dashboard interface for Managers to view the weekly summary of the staff availability and workload. 
FR2: The system shall allow Managers to sort the weekly summary by different staff roles for effective planning. 
FR3: The system shall provide a user interface for Managers to assign jobs to the different staff members for each shift. 
FR4: Managers shall be presented with details of up to 3 staff members for consideration when assigning jobs. 
FR5: The system shall allow Managers to re-allocate jobs for each staff and shift.  
FR6: The system shall allow Managers to allocate jobs according to the staff preferences and availability. 
FR7: The system shall allow Managers to view the details of each staff allocated. 
FR8:The system shall provide a user interface for Managers to view all staff members in a table.  
FR9: The system shall allow Managers to search for a specific staff member by Name. 
FR10: The system shall allow Managers to sort the display table with options of no sort, least amount of hours worked per week, and most amount of hours worked per week.  
FR11: The system shall update job allocations in real-time to allow Managers to allocate jobs for staff that might be affected by previous shifts allocated. 
FR12: The system shall provide a user interface for Managers to view all notifications received. 
FR13: The system shall allow Managers to take action for job requests received. 
FR14: The system shall allow Managers to contact staff members through the system. 
FR15: The system shall allow Managers to contact IT admins through the system.

**Comment by alanwml** [comment]
Created additional starting FRs on 12/09/23 :

FR16: The system shall provide a user interface for staff members to view their job schedule. 
FR17: The system shall allow staff members to submit their job preferences through the system. 
FR18: The system shall allow staff members to modify their job preferences.
FR19: The system shall allow staff members to reject jobs allocated to them.
FR20: The system shall allow staff members to view the details of the job allocated to them.
FR21: The system shall provide staff members to view all notifications received.
FR22: The system shall notify staff members for jobs allocated to them. 
FR23: The system shall allow staff members to contact Managers through the system.
FR24: The system shall allow staff members to contact IT admins through the system.
FR25: The system shall allow IT admins to create new accounts for different account types.
FR26: The system shall allow IT admins to delete any accounts in the system. 
FR27: The system shall allow IT admins to modify accounts in the system.
FR28: The system shall allow IT admins to view all accounts in the system.
FR29: The system shall allow IT admins to search for a specific account in the system.
FR30: The system shall allow IT admins to contact any staff through the system.
FR31: The system shall allow all staff members to modify the display photo and password of their account.

**Comment by alanwml** [comment]
TBD

**Comment by git-clone-xen** [comment]
# Issue Comments

## Description
- Analyzed initial requirements and studied insights provided by the client
- Crafted a list of functional requirements according to the information acquired.

## Changes to success or completion criteria? y/n (if y, describe)
No changes, Criteria Completed.

Start Date: 08/09/23, 0900
End Date: 13/09/23, 2359
