### ISSUE TITLE
[1.3.3] Non-Functional Requirements

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#27]
# Issue Details

### Description
Come up with a list of non-functional requirements for the project and validate all of them. This is to help specify additional important requirements that the system should achieve, such as usability requirements.

### Success or Completion Criteria
A completed and validated list of All non-functional requirements.
- [x] #40 
- [x] #41 
- [x] #32 
- [x] #83 
- [x] #60 
- [x] #66 

### Allocated Time
9 Days

**Start Date:** 08/09/23, 0900
**End Date:** 13/09/23, 2359

**Comment by waafi-adam** [comment]
Commented all the Non functional requirements with suggested improvements. Though might need to check if there are repeated requirements

**Comment by alanwml** [comment]
# Issue Comments

## Description
Completed all the Sub-Issues that are required for Non-Functional Requirements.

## Changes to success or completion criteria? y/n (if y, describe)
No Changes, Criteria Completed.

Start Date: 08/09/23, 0900
End Date: 13/09/23, 2359
