### ISSUE TITLE
Team Meeting Minutes #2

### ISSUE THREAD

**Issue by alanwml** [Alan2201038/INF2001-P5-7#28]
Description: Discussion that took placed during Team Meeting.

Goals: Document Minutes.

Success or Completion Criteria: Minutes Text

Allocated Time: 1 Day

Start Date: 07/09/23
End Date: 07/09/23, 2359

**Comment by waafi-adam** [comment]
**Shift Assignment System Overview**

**1. Shift Selection by Employees:**
- Employees can pick shifts based on 4-hour blocks.

**2. Performance Display:**
- At the end of the week, the system will display performance metrics for both the top 3 and the lowest 3 employees. The metrics will include:
  - Total hours worked.
  - Number of weekends worked.
  - Extra carriages managed during the week.

**3. Assignment Criteria:**
- Employees will be ranked based on total hours worked.
- If a worker hasn't chosen a shift by Wednesday, the system will consider them as having "no preference" and mark them as available all day.

**4. Staff Location:**
- Before assigning a shift, the system should be aware of the last worked location of an employee to ensure efficient positioning.
- The indication of a staff member's location is critical both before and after their shift to help in planning and scheduling.

**Questions to Consider:**

1. Are there maintenance/servicing crew? Yes/No
2. Does the manager need to know if a train is currently undergoing or requires maintenance? Yes/No
3. If the answer to the above question is YES, does the manager need to assign staff specifically for this maintenance?
4. When considering workload:
    - Should the system display the top 3 staff from all roles with the least workload + all staff who have worked 40 hours?
    - Or should the system filter and show this data role by role?

**Note**: These insights will help in refining the system's design and ensuring its efficiency. @ @

**Comment by waafi-adam** [comment]
# Issue Comments

## Description
complete minutes meeting as above

## Changes to success or completion criteria? y/n (if y, describe)
n

# Issue Comments

## Description
Compared the different approaches and justified reason for choosing Use Case Points method for our estimations

## Changes to success or completion criteria? y/n (if y, describe)
n

**Start Date:** 19/09/23, 0900
**End Date:** 20/09/23, 2359
