### ISSUE TITLE
[1.2.3] Follow-Up Email #1

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#29]
# Issue Details

## Description
The aim of this follow-up email is to address any outstanding concerns, clarify any ambiguities from our previous meetings, verify the key points that was talked about during the previous meeting and analyzing the response given by out client if he chooses to respond.

## Goals
The goal is to get an email sent to the client, asking him to validate our previous meeting points and respond to our clarification and queries. Afterwards analyze the client's response to get a further improved understanding of our client's requirement.

## Success or Completion Criteria

- [x] #54 
- [x] #58 

## Allocated Time
1 Day to send Email
? Days to analyze a possible Response Email.

**Start Date:** 07/09/23, 1100
**End Date:** 07~??/09/23, 2359

**Comment by nadhirah5** [comment]
# Issue Comments

## Description
Successfully sent out follow-up email to client and analyzed client's email response

## Changes to success or completion criteria? y/n (if y, describe)
y, Client did not email us back, moving the Analyze Issue to the Backlogs.

**Start Date:** 07/09/23, 1100
**End Date:** 22/09/23, 2359
