### ISSUE TITLE
[1.3.3.3] Validate RURs, PRs & SSRs

### ISSUE THREAD

**Issue by alanwml** [Alan2201038/INF2001-P5-7#32]
### Description
Validate Non-Functional Requirements (NFRs), to make sure our NRFs are up to standard based on the 7 aspects that makes a good Requirement.

### Success or Completion Criteria
A list of valid NFRs in our Report

- [x] #72 
- [x] #62 

### Allocated Time 
4 Days

**Start Date:** 08/09/23, 0900
**End Date:** 13/09/23, 2359

**Comment by Alan2201038** [comment]
Updated this Issue, to be split among 4 assignees into 2 different Sub-Issues, therefore the deadline will be extended by 3 days.

### Allocated Time
5 days

Start Date: 10/09/23, 2200
End Date: 15/09/23, 2359

**Comment by pangyurui** [comment]
Checked through all existings NFRs and added comments which will be used to clarify the accuracy of NFRs with the client.

**Comment by pangyurui** [comment]
Updated the NFRs based on input received after seeking confirmation about uncertainties with the client.

**Comment by waafi-adam** [comment]
made revision based on NFR for completeness and ensure they meet idustrial standards

**Comment by pangyurui** [comment]
# Issue Comments

## Description
Validated all RURs, PRs & SSRs in the report.

## Changes to success or completion criteria? y/n (if y, describe)
n

Start Date: 08/09/23, 0900
End Date: 13/09/23, 2359
