### ISSUE TITLE
[1.4.4.2] Create Use Case Descriptions

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#33]
# Issue Details

### Description
Come up with the use case descriptions for each of the use cases which we have identified. This allows stakeholders to better understand what the use case is about and additional details such as alternate flows. It is also required to determine cost and effort estimation. 

### Success or Completion Criteria
Completed use case descriptions for all use cases.

### Allocated Time
4 Days

**Start Date:** 14/09/23, 0000
**End Date:** 19/09/23, 2359

**Comment by waafi-adam** [comment]
Completed use cases decriptions for involving actor manager, UC-9 to UC-15

**Comment by pangyurui** [comment]
Completed use case descriptions for employees, UC-5 to UC8.

**Comment by motorfireman** [comment]
### Description: 
Taken over from Yu Rui and Waafi. Reduced the number of use case description as some can be generalized to avoid double counting of transaction cost.

The final Use case diagram is attached.

[P5-G7_INF2001_UseCaseDiagram_M1_Fig4.pdf](https://github.com/Alan2201038/INF2001-P5-7/files/12682905/P5-G7_INF2001_UseCaseDiagram_M1_Fig4.pdf)



### Changes to success or completion criteria? Y/N (if yes, describe): 
No

Start Date: 14/09/23, 0000
End Date: 19/09/23, 2359
