### ISSUE TITLE
[1.4.2.2] Create & Validate Product Functionalities

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#35]
# Issue Details

### Description
Create and analyze the product functionalities by checking them against the 7 factors that make a requirement good. This ensures that the product functionalities are well documented and can be easily understood.

### Success or Completion Criteria
Product functionalities that satisfy all 7 factors of what makes a requirement good.

### Allocated Time
2 days

**Start Date:** 08/09/23, 0900
**End Date:** 11/09/23, 2359

**Comment by motorfireman** [comment]
### Description: 
Consulted with professors, PF currently do not need to adhere to the 7 aspect.

### Changes to success or completion criteria? Y/N (if yes, describe): 
Yes. As described in the description.

Start Date: 08/09/23, 0000
End Date: 11/09/23, 2359
