### ISSUE TITLE
[1.4.6.1] Generate a Project Management Gantt Chart

### ISSUE THREAD

**Issue by pangyurui** [Alan2201038/INF2001-P5-7#36]
# Issue Details

### Description
Create a gantt chart to aid with project management and provide an overview of what is required to be done over the next 12 weeks. The gantt chart should include tasks for all 3 milestones. 

### Success or Completion Criteria
Gantt chart with realistic requirements that cover >= 95% of the project.

### Allocated Time
3 Days

**Start Date:** 20/09/23, 0900
**End Date:** 22/09/23, 2359

**Comment by motorfireman** [comment]
### Description: 
Create a Gantt chart based on the WBS and included milestone 1 to 3.

[P5-G7_INF2001_GanttChart_M1_Fig7.pdf](https://github.com/Alan2201038/INF2001-P5-7/files/12682896/P5-G7_INF2001_GanttChart_M1_Fig7.pdf)



### Changes to success or completion criteria? Y/N (if yes, describe): 
No

Start Date: 20/09/23, 0900
End Date: 22/09/23, 2359
