### ISSUE TITLE
[1.4.5.2] Creating Work Breakdown Structure

### ISSUE THREAD

**Issue by alanwml** [Alan2201038/INF2001-P5-7#37]
### Description
Creating a Work Breakdown Structure (WBS), to define and organize the work required for M2, M3 and the remainder of M1.

### Success or Completion Criteria
- An image of our WBS in here and our report.

### Allocated Time
3 Days.

**Start Date:** 19/09/23, 0900
**End Date:** 21/09/23, 2359

**Comment by pangyurui** [comment]
Wrote a draft of the WBS which contain the outlines of the main activities.

**Comment by pangyurui** [comment]
Created an initial WBS using lucidchart.

**Comment by pangyurui** [comment]
Reformatted the WBS to ensure that it can fit within a single page whilst maintaining readability.

**Comment by pangyurui** [comment]
Updated the numbering of the tasks in the WBS.

**Comment by pangyurui** [comment]
# Issue Comments

## Description
Completed the WBS and added it into the report.

## Changes to success or completion criteria? y/n (if y, describe)
n

Start Date: 19/09/23, 0900
End Date: 21/09/23, 2359
