### ISSUE TITLE
Set up our Project Wiki.

### ISSUE THREAD

**Issue by Alan2201038** [Alan2201038/INF2001-P5-7#4]
Have to set-up a README.md for our Github Repository. It must include:
- [x] Introduction of Group Project
- [x] How team intends to address the problem for our Project.
- [x] Team Members and their Roles.

**Comment by alanwml** [comment]
# Issue Comments

## Description
Summary: Created a README.md File and Uploaded it in our Github Repository [Here](https://github.com/Alan2201038/INF2001-P5-7/blob/main/README.md)!

## Changes to success or completion criteria? y/n (if y, describe)
Completion Criteria all satisfied!

Start Date: 29/08/23, 1700
End Date: 30/08/23, 2359
