### ISSUE TITLE
[1.3.3.1] Create RURs, PRs & SSRs.

### ISSUE THREAD

**Issue by alanwml** [Alan2201038/INF2001-P5-7#40]
# Issue Details

### Description
To Create Reliability & Usability Requirements (RURs), Performance Requirements (PRs) and Safety & Security Requirements (SSRs). This is a subset of the Non-Functional Requirements to help specify additional important requirements based on the above mentioned topics.

### Success or Completion Criteria
A list of Non-Functional Requirements (NFRs) based on these 3 types of NFRs.

- [x] #65 
- [x] #61 

### Allocated Time
4 Days

**Start Date:** 08/09/23, 0900
**End Date:** 13/09/23, 2359

**Comment by pangyurui** [comment]
# Issue Comments

## Description
Finalised the list of RURs, PRs & SSRs in the report.

## Changes to success or completion criteria? y/n (if y, describe)
n

Start Date: 08/09/23, 0900
End Date: 13/09/23, 2359
