### ISSUE TITLE
[1.3.3.2] Create DTs, DSs & ORs.

### ISSUE THREAD

**Issue by alanwml** [Alan2201038/INF2001-P5-7#41]
# Issue Details

### Description
To Create Data Transfer Requirements (DTs), Data Storage Requirements (DSs) and Other Requirements (ORs). This is a subset of the Non-Functional Requirements to help specify additional important requirements based on the above mentioned topics.

### Success or Completion Criteria
A list of Non-Functional Requirements (NFRs) based on these 3 types of NFRs.

- [x] #73 
- [x] #77 

### Allocated Time
4 days

**Start Date:** 08/09/23, 0000
**End Date:** 13/09/23, 2359

**Comment by nadhirah5** [comment]
# Issue Comments

## Description
Successfully completed list of Non-Functional Requirements

## Changes to success or completion criteria? y/n (if y, describe)
n

**Start Date:** 08/08/23, 0000
**End Date:** 13/09/23, 2359
