### ISSUE TITLE
Request a meeting with Client for Consultation

### ISSUE THREAD

**Issue by Alan2201038** [Alan2201038/INF2001-P5-7#5]
Need to email our Client, Mr. Quah, to request a 15-minute face to face consultation about the project.

To try set the meeting up on 5th September 2023, 2pm in SIT NYP. However it is not a must, schedule is flexible.

Deadline: 30/08/2023

**Comment by alanwml** [comment]
## Issue Comments

### Description:
I have booked a meeting for my team and I with the Client on 7th September @ 11am. The location will be SIT@NYP, DR-2A.

### Changes to success or completion criteria?: y/n (if y, describe)
Changed from Email to Booking Via Excel Sheet, other than that, Issue was successfully completed.

Start Date: 29/08/23, 1800
End Date: 30/08/23, 2359
