### ISSUE TITLE
[1.2.3.2] Analyze Response Email

### ISSUE THREAD

**Issue by motorfireman** [Alan2201038/INF2001-P5-7#58]
# Issue Details

## Description
This sub issue is for me to analyze the client's response to our follow-up email #1, to have a better understanding of our Client's POV and also to rectify any ambiguous requirements.
**Note: This Issue can only be started IF the Client responded to our Email**

## Goals
I will analyze and summarize the Client's response. Afterwards I will share this information with my group mates to rectify any issues that my group has with the current requirements.

## Success or Completion Criteria
Have a summary of the key points that was gathered by the Client's response.

## Allocated Time
2 Days

**Start Date:** When the Client Respond.
**End Date:** 2 Days after the Client Respond.

**Comment by motorfireman** [comment]
### **Description:** 
Client generally okay with any proposed NFR as long as it is reasonable. The focus shouldn't be too much on the security but rather the functionality.

### **Changes to success or completion criteria? Y/N (if yes, describe):** 
No

Start Date: 18/09/23, 1800
End Date: 18/09/23, 2359

**Comment by alanwml** [comment]
# Issue Comments

## Description
Client did not emailed back to us.

## Changes to success or completion criteria? y/n (if y, describe)
Yes, changed issue to backlog as this issue is not completed.

Start Date: 19/09/23, 0900
End Date: 19/09/23, 1500
