### ISSUE TITLE
M1 Documentation [1st Revision]

### ISSUE THREAD

**Issue by Alan2201038** [Alan2201038/INF2001-P5-7#7]
Documenting our Milestone 1 progress.

**Comment by motorfireman** [comment]
Created an outline of the report. Included supporting guides and comments on what is required per section as minimum. Clarification of certain section is needed before embarking on writing.

**Comment by waafi-adam** [comment]
create data dictionary with 20-30 dictionaries

**Comment by waafi-adam** [comment]
created System Architecture Diagram

**Comment by alanwml** [comment]
Summary of what has been Completed:
 - Outline of Report
 - Data Dictionary
 - System Architecture Diagram
 - A list of Functional Requirements
 - A list of Non-Functional Requirements

Reason for Closing Issue:
- Creating a new issue to track our documentation progress clearly.
