### ISSUE TITLE
[1.1.1] Domain Research

### ISSUE THREAD

**Issue by waafi-adam** [Alan2201038/INF2001-P5-7#70]
# Issue Details

### Description
This main issue is for us to do a background research on our Project Domain, which is about the Train Services Workload Management System. 

### Goals
To have a better understanding of the Train Service Day to Day Operation, the employees working in the Train Operations Department and their current workload management systems. We will then share our findings with the rest of the group.

### Success or Completion Criteria

- [x] #50 
- [x] #56 

### Allocated Time
2 Days

**Start Date:** 29/08/23, 1800
**End Date:** 30/08/23, 2359

**Comment by nadhirah5** [comment]
# Issue Comments

## Description
Completed research on trains and train employees

## Changes to success or completion criteria? y/n (if y, describe)
n

**Start Date:** 29/08/23, 1800
**End Date:** 30/08/23, 2359
