### ISSUE TITLE
[1.1] Project Research

### ISSUE THREAD

**Issue by waafi-adam** [Alan2201038/INF2001-P5-7#71]
# Issue Details

## Description
This task is for us to do pre-learning about our project and also do our independent research on the project domain to be prepared for the Trimester.

## Goals
We have a better understanding on our Project Domain, Semi-Structured Interviews and Project Description.

## Success or Completion Criteria

- [x] #70 
- [x] #55 
- [x] #52 

## Allocated Time
2 Days

**Start Date:** 29/08/23, 1800
**End Date:** 30/08/23, 2359

**Comment by nadhirah5** [comment]
# Issue Comments

## Description
Successfully completed conducting domain research, understanding semi-structured interview and project description

## Changes to success or completion criteria? y/n (if y, describe)
n

**Start Date:** 29/08/23, 1800
**End Date:** 30/09/23, 2359
