### ISSUE TITLE
Initial Requirement 5 Lofi-Prototyping

### ISSUE THREAD

**Issue by Alan2201038** [Alan2201038/INF2001-P5-7#8]
Description: Prototyping based on Initial Requirement 5. 

Goals: Create a Prototype based on the Requirement.

Success or Completion Criteria: Prototype Figma.

Allocated Time: 1 day

Start Date: 01/09/23
End Date: 01/09/23

Main Task :  [Create lo-fi prototypes/wireframes based for the initial requirements](https://github.com/Alan2201038/INF2001-P5-7/issues/6)

**Comment by pangyurui** [comment]
test

**Comment by Alan2201038** [comment]
Done!

![Image](https://github.com/Alan2201038/INF2001-P5-7/assets/113186322/9b6554bf-c714-4ef6-8ca9-85f403e289ff)
![Image](https://github.com/Alan2201038/INF2001-P5-7/assets/113186322/a95b0c5f-b182-4967-a7b8-1d1fba54d373)
![Image](https://github.com/Alan2201038/INF2001-P5-7/assets/113186322/09231fc0-fc88-452c-9fa9-d83474724d29)
